FROM python:3.9-slim  # Use a slim Python image for a smaller container footprint

WORKDIR /app  # Set the working directory within the container

COPY requirements.txt .  # Copy requirements.txt to the container

RUN pip install -r requirements.txt  # Install dependencies from requirements.txt

COPY . .  # Copy your application code to the container

EXPOSE 5000  # Expose the port where the Flask app runs (default for Flask)

CMD ["python", "app.py"]  # Set the command to run your application (replace app.py with your main Python script name)
